### ISSUE TITLE
Does VoLTE and WiFi Calling work?

### ISSUE THREAD

**Issue by lucasmz-dev** [SamarV-121/android_device_samsung_m20lte#10]
I know this seems to be like some big annoying question because of r/LineageOS having a rule about it, and I actually am not able to install lineageOS or tinker with my phone because my USB connection is very unstable because the ports & cable are pretty damaged at this point, but I have been looking around carriers and while none actually offers complete WiFi Calling with SMS and so no dependence on expensive-to-battery radio towers, I am in the process of switching to that one, and getting the service activated, but I have just remembered this and I really wanted to know if it works or not and if realibly, and if it DOES INFACT WORK, of if its just the icon, you can make sure of that by deactivating WiFi and checking if the symbol of your data connection changes from 4G/LTE to something worse.

**Comment by SamarV-121** [comment]
No, it doesn't work on any samsung device as of now

**Comment by lucasmz-dev** [comment]
<s> So LineageOS does not support it? </s>

Just found about why. (which is because Samsung's implementation is apparently proprietary) (someone needs to put laws in place cuz this shouldnt be allowed how is it not a standard what the hell)
