### ISSUE TITLE
Charging Animation (AOSP 12)

### ISSUE THREAD

**Issue by i0x404** [SamarV-121/android_device_samsung_m20lte#6]
Hello,
I found out that there is no charging animation when charging the phone and turned off it's just a black screen.

**Comment by SamarV-121** [comment]
Will be fixed in upcoming LineageOS-19.0

**Comment by SamarV-121** [comment]
Will be fixed in upcoming LineageOS-19.0

**Comment by userariii** [comment]
@SamarV-121 Hey, how did u fix the charging animation issue?
