### ISSUE TITLE
OK to install on android 10?

### ISSUE THREAD

**Issue by cachiusa** [SamarV-121/android_device_samsung_m20lte#7]
The image on twrp site seems to be made for android 9(twrp-3.6.2_9-0-m20lte.img.tar) but I am having the latest official version(10). Should I proceed with installing twrp?

**Comment by SamarV-121** [comment]
sure

**Comment by cachiusa** [comment]
And how am I gonna deal with the os when it forces me to wipe and relock bootloader?

**Comment by SamarV-121** [comment]
Not sure what you are talking about

**Comment by cachiusa** [comment]
Yes I know you warned about the dm-verity thing but what should I do about that?
Even if I installed twrp successfully the phone will ask you to reset because of 'Verification failed'
