### ISSUE TITLE
USB file transfer not working

### ISSUE THREAD

**Issue by LightWilliamz** [SamarV-121/android_device_samsung_m20lte#8]
USB file transfer not working
restart phone and PC
still not work
ig it is a bug

**Comment by SamarV-121** [comment]
on LineageOS? try turning USB debugging off

**Comment by LightWilliamz** [comment]
Still not fixed the issue
only charging the phone

**Comment by LightWilliamz** [comment]
I even reset my phone and PC
still not work 
even USB configuration is missing in dev mode.

**Comment by LightWilliamz** [comment]
nvm i found USB config and fixed the problem by your tip
thx

**Comment by LightWilliamz** [comment]
thx for making android 12.1 for M20 and love you even you are not a maintainer of offcial linage os
